// WORKSPACE
export const SAVE_WORKSPACE_CODE = 'SAVE_WORKSPACE_CODE';
export const SAVE_WORKSPACE_PSEUDOCODE = 'SAVE_WORKSPACE_PSEUDOCODE';
export const SAVE_WORKSPACE_PSEUDOCODE_ERROR = 'SAVE_WORKSPACE_PSEUDOCODE_ERROR';
export const SAVE_WORKSPACE_AST = 'SAVE_WORKSPACE_AST';
export const SAVE_WORKSPACE_AST_ERROR = 'SAVE_WORKSPACE_AST_ERROR';
export const SAVE_WORKSPACE_JAVASCRIPT = 'SAVE_WORKSPACE_JAVASCRIPT';
export const SAVE_WORKSPACE_JAVASCRIPT_ERROR = 'SAVE_WORKSPACE_JAVASCRIPT_ERROR';

// LOGIN
export const REQUEST_LOGIN_USER = 'REQUEST_LOGIN_USER';
export const REQUEST_LOGIN_USER_SUCCESS = 'REQUEST_LOGIN_USER_SUCCESS';
export const REQUEST_LOGIN_USER_ERROR = 'REQUEST_LOGIN_USER_ERROR';

// TUTORIAL
export const START_TUTORIAL = 'START_TUTORIAL';
export const FINISH_EXERCISE = 'FINISH_EXERCISE';
export const GET_NEXT_EXERCISE = 'GET_NEXT_EXERCISE';

// EXERCISES
export const GET_CURRENT_EXERCISE = 'GET_CURRENT_EXERCISE';