// WORKSPACE
export const SAVE_WORKSPACE_CODE = 'SAVE_WORKSPACE_CODE';
export const SAVE_WORKSPACE_PSEUDOCODE = 'SAVE_WORKSPACE_PSEUDOCODE';
export const SAVE_WORKSPACE_PSEUDOCODE_ERROR = 'SAVE_WORKSPACE_PSEUDOCODE_ERROR';
export const SAVE_WORKSPACE_AST = 'SAVE_WORKSPACE_AST';
export const SAVE_WORKSPACE_AST_ERROR = 'SAVE_WORKSPACE_AST_ERROR';
export const SAVE_WORKSPACE_JAVASCRIPT = 'SAVE_WORKSPACE_JAVASCRIPT';
export const SAVE_WORKSPACE_JAVASCRIPT_ERROR = 'SAVE_WORKSPACE_JAVASCRIPT_ERROR';
export const CLEAN_WORKSPACE = 'CLEAN_WORKSPACE';

// LOGIN
export const REQUEST_LOGIN_USER = 'REQUEST_LOGIN_USER';
export const REQUEST_LOGIN_USER_SUCCESS = 'REQUEST_LOGIN_USER_SUCCESS';
export const REQUEST_LOGIN_USER_ERROR = 'REQUEST_LOGIN_USER_ERROR';

// TUTORIAL
export const SET_EXERCISE_DONE = 'SET_EXERCISE_DONE';
export const GET_NEXT_EXERCISE = 'GET_NEXT_EXERCISE';
export const COMPLETE_EXERCISE = 'COMPLETE_EXERCISE';

// EXERCISES
export const GET_CURRENT_EXERCISE = 'GET_CURRENT_EXERCISE';