// AUTH
export const REQUEST_LOGIN_USER = 'REQUEST_LOGIN_USER';
export const REQUEST_LOGIN_USER_SUCCESS = 'REQUEST_LOGIN_USER_SUCCESS';
export const REQUEST_LOGIN_USER_ERROR = 'REQUEST_LOGIN_USER_ERROR';